FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY python ./python
COPY server.py .
COPY public ./public

CMD ["python", "server.py"]
